name: "postprocess"

backend: "python"

max_batch_size: 512

input [
    {
        name: "input_text"
        data_type: TYPE_STRING
        dims: [ 1 ]
    }
]

input [
  {
    name: "classes"
    data_type: TYPE_INT64
    dims: [ -1 ]
  }
]

input [
  {
    name: "offset_mapping"
    data_type: TYPE_INT64
    dims: [ -1, 2 ]
  }
]

output [
  {
    name: "valid"
    data_type: TYPE_BOOL
    dims: [ -1 ]
  }
]

output [
  {
    name: "token_array"
    data_type: TYPE_STRING
    dims: [ -1 ]
  }
]

output [
  {
    name: "class_name_array"
    data_type: TYPE_STRING
    dims: [ -1 ]
  }
]


instance_group [
    {
        count: 3
        kind: KIND_CPU
    }
]
